### PR TITLE
Grove sensors

### PR DESCRIPTION
**Pull request by edersondisouza**
Nodes for three analogic sensors of Galileo Grove Kit that would demand some calculation over raw readings to be useful: temperature, light and rotary. The idea is to provide a simple way to use these analogic sensors.
It depends on pull req #25 (I've included its commits in this pull req).

### CODE REVIEW

**Comment by dorileo** [comment]
seems these murillo's patches don't belong here, doesn't it?

**Comment by edersondisouza** [comment]
If one wants to test, those patches will be needed. That's why I've said that it depends on pull #25.

**Comment by dorileo** [comment]
all right...

**Comment by edersondisouza** [comment]
V2 on #52

**Pull request closed without merging**
