### PR TITLE
Add support for array ports

### PR DESCRIPTION
**Pull request by ibriano**
This patch set adds support to generate node types using array ports,
instead of having several ports that will use the same set of functions.

The parser is changed to understand the notation PORT[idx] and the
necessary work in the building blocks is done to turn said notation
into the port numbers that the base framework undestands.

Exporting ports from an FBP file can be done by exporting individual
members of an array, using the corresponding index, or if no index is
given, the entire array is exported.

A few node types have been converted to use these feature to show case
it.

### CODE REVIEW

**Comment by lpereira** [comment]
:+1:

**Comment by bdilly** [comment]
Series seems good

**Comment by ibriano** [comment]
Merged

**Comment by cmarcelo** [comment]
+2 (late in the game)

**Pull request closed without merging**
