### PR TITLE
Node.js bindings: Adapt JS bindings to the latest API changes

### PR DESCRIPTION
**Pull request by nagineni**
Adapt AIO,SPI and I2C JS bindings to the latest API changes.

Replaces #2129 
 
Signed-off-by: Sudarsana Nagineni sudarsana.nagineni@intel.com

### CODE REVIEW

**Comment by nagineni** [comment]
@gabrielschulhof Fixed all review comments. PTAL.

**Comment by gabrielschulhof** [comment]
https://github.com/solettaproject/soletta/pull/2153/files#diff-a92bf7b9ffd390afbb1cb2e29fa6fc62L19 should also ```require( "./lowlevel" );```

**Comment by gabrielschulhof** [comment]
Aside from that, it's :+1

**Comment by nagineni** [comment]
@gabrielschulhof thanks!

> https://github.com/solettaproject/soletta/pull/2153/files#diff-a92bf7b9ffd390afbb1cb2e29fa6fc62L19 should also require( "./lowlevel" );

AIO is not using ReverseLookup mechanism, so no need to `require( "./lowlevel" );`

**Pull request closed without merging**
