### PR TITLE
Sol-buffer: Use SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED at SOL_BUFFER_DECLA…

### PR DESCRIPTION
**Pull request by cabelitos**
…RE_STATIC()

Otherwise if one tries to sol_buffer_fini(&buf), soletta would crash.

Signed-off-by: Guilherme Iscaro <guilherme.iscaro@intel.com>

### CODE REVIEW

**Comment by cabelitos** [comment]
I just wanted to init things..

**Comment by barbieri** [comment]
answering @otaviobp, it is a good practice to `sol_buffer_fini()` stuff. I see that @cabelitos did most of his patch without doing so, it's okay since memory-not-owned does nothing in the fini, but if one converts that to dynamic, then we start to leak.

**Comment by otaviobp** [comment]
Sorry if I wasn't very clear. I was saying about zeroing the "name_ ## storage" variable. This is not added in this patch, but I saw that in this review.

**Comment by cabelitos** [comment]
Can I merge this?

**Comment by otaviobp** [comment]
yep

**Comment by cabelitos** [comment]
merged

**Pull request closed without merging**
