### PR TITLE
Sol-worker-threads: API changes

### PR DESCRIPTION
**Pull request by kaspersky**
#1699

### CODE REVIEW

**Comment by glima** [comment]
The bindings are failing at our CI build, but the patch seems OK.

**Comment by glima** [comment]
@gabrielschulhof, have you seen that?

**Comment by cabelitos** [comment]
@glima https://github.com/solettaproject/soletta/pull/1693

**Comment by cabelitos** [comment]
+1

**Comment by otaviobp** [comment]
this pr lgtm. The build error is not related to this pr

**Comment by otaviobp** [comment]
merged

**Pull request closed without merging**
