### PR TITLE
Add the correct dependencies for samples

### PR DESCRIPTION
**Pull request by cabelitos**

### CODE REVIEW

**Comment by edersondisouza** [comment]
Looks OK. But I didn't double check dependencies =D

**Comment by cabelitos** [comment]
I updated the PR. Fixing a type at 2fb4221 and add more missing dependencies.

**Comment by cabelitos** [comment]
@edersondisouza I created a script to do that :]

**Comment by bdilly** [comment]
@cabelitos where is this script?

I believe you could push it to our repo so other may use it in the future

**Comment by edersondisouza** [comment]
On 30-03-2016 14:46, Bruno Dilly wrote:
> @cabelitos <https://github.com/cabelitos> where is this script?
>
> I believe you could push it to our repo so other may use it in the future

A script that checks it? Could even be part of tests that we run on CI?

**Comment by cabelitos** [comment]
@bdilly @edersondisouza I will add it to the CI. soon I will create a PR with it.

**Comment by cabelitos** [comment]
#1788

**Pull request closed without merging**
