### PR TITLE
oic-samples: Some small improvements.

### PR DESCRIPTION
**Pull request by otaviobp**

### CODE REVIEW

**Comment by glima** [comment]
OK, for me.

**Comment by cabelitos** [comment]
+1

**Comment by otaviobp** [comment]
Answering ceolin. Before this patch I used NULL resource for scanning and core.light for everything else. With this patch we use the argument value, if informed, for everything, even scanning. I think this is a better approach to make easier to test scanning with filters.
If I have a default value, it would be hard to test the sample using NULL resource type.

**Comment by otaviobp** [comment]
merged and closed.

**Pull request closed without merging**
