### PR TITLE
datatypes: Make room for the nul char at the end of the string

### PR DESCRIPTION
**Pull request by ibriano**

### CODE REVIEW

**Comment by dorileo** [comment]
+1

**Comment by ibriano** [comment]
Merged

**Comment by barbieri** [comment]
doesn't hurt, but I wonder why... It's a map, not a string :-D

**Comment by ibriano** [comment]
On Fri, 09 Oct 2015 12:17:03 -0700, Gustavo Sverzut Barbieri wrote:
> doesn't hurt, but I wonder why... It's a map, not a string :-D

The node type is using `streq()` on the map it gets from the options
with this one to see if they are equal, which then tries to read the
final \0 that's not part of the array declared size. Probably should
have changed that call to use strneq instead, but I saw that afterwards.

**Comment by barbieri** [comment]
then my code, my bad... autospank :-D

**Pull request closed without merging**
