### PR TITLE
sol-conffile: Remove quotes from strings

### PR DESCRIPTION
**Pull request by bdilly**
When an options is a string, the quotes should be
removed from it.

Signed-off-by: Bruno Dilly <bruno.dilly@intel.com>

### CODE REVIEW

**Comment by bdilly** [comment]
@cabelitos please test it and see if it solves your issues.

@barbieri pointed out that we're missing a function to handle escape codes:

escapable_chars[] = {'\\', '\"', '/', '\b', '\f', '\n', '\r', '\t'};

so I've added that to my todo list. But based on your previous PR, I believe it's not impacting you.

**Comment by glima** [comment]
We already have that in our parser, don't we?

**Comment by cabelitos** [comment]
@glima Yes, there's a unesacape_string function.

Btw, this patch fix the problem for me.
Should I close my pullreq?

**Comment by bdilly** [comment]
@glima @cabelitos yeah, we have it in our flow parser indeed.
So maybe it's just a matter of exposing it in our json parser lib.
I'll take a look on that soon.
Thanks

Merged

**Pull request closed without merging**
