### PR TITLE
iio/i2c: configure pinmux before load I2C device drivers

### PR DESCRIPTION
**Pull request by yongli3**
On some platforms(Galileo/Edison), these GPIO pins must be configured before using I2C bus
This patch perform the pin mux configuration before loading I2C device drivers

Signed-off-by: Yong Li <yong.b.li@intel.com>

### CODE REVIEW

**Comment by yongli3** [comment]
@bdilly @edersondisouza @mbelluzzo @cabelitos @barbieri please review

**Comment by mbelluzzo** [comment]
+1

**Comment by edersondisouza** [comment]
looks ok

**Comment by edersondisouza** [comment]
Integrated. Tks @yongli3 !

**Pull request closed without merging**
