### PR TITLE
Duktape [v2]

### PR DESCRIPTION
**Pull request by glima**
Only to be applied after solettaproject/duktape-release#4 gets in.

Changes since #1448:
- one more commit fixing an old duktape bad usage
- rebased to new master

### CODE REVIEW

**Comment by cabelitos** [comment]
+1

**Comment by edersondisouza** [comment]
looks ok

**Comment by bdilly** [comment]
that's ok. just make sure you're testing all our samples before merging please

**Comment by glima** [comment]
I did. Merging.

**Pull request closed without merging**
