### PR TITLE
docs: include C API examples

### PR DESCRIPTION
**Pull request by bdilly**

### CODE REVIEW

**Comment by barbieri** [comment]
Can we auto generate this list with "find" so we don't need to maintain it manually?

**Comment by bdilly** [comment]
Do you mean using a src/lib/common/include/sol-mainloop.h.in to generate a final sol-mainloop.h when we build?

**Comment by barbieri** [comment]
It seems we have docs/doxygen/examples.dox that is empty. We could move the Doxyfile to include build/stage/docs/doxygen/examples.dox (or something like that) from:

mkdir -p build/stage/docs/doxygen
cp docs/doxygen/examples-header.dox build/stage/docs/doxygen/examples.dox
find src/samples -type f -printf "@example %h/%f\n" >> build/stage/docs/doxygen/examples.dox

**Comment by bdilly** [comment]
merged with proposed changes

**Pull request merged**
