### PR TITLE
Normalizing user data pointer

### PR DESCRIPTION
**Pull request by ceolin**
https://github.com/solettaproject/soletta/issues/1269

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by cabelitos** [comment]
If I remenber right, the data should be the first parameter of the callbacks as well
@barbieri ^

**Comment by ceolin** [comment]
I think so, but i prefer do not mix things here, also the issue itself it's not telling anything about the order.

**Comment by cabelitos** [comment]
Well, I'm saying that, because he warned to me about this issue.
Anyway +1

**Comment by ceolin** [comment]
i know, i just think they are different/separated fixes

**Comment by barbieri** [comment]
+1

**Pull request merged**
