### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by glima**
Some fixes I detected while running checks here. What triggered them where mostly the python thing, which is blocking F26 versioned packages on Fedora to build.

### CODE REVIEW

**Comment by glima** [comment]
@cabelitos and @ceolin, whenever you can, please :)

**Comment by glima** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1424460
ETA next week's beginning for merging this.

**Comment by cabelitos** [comment]
lgtm

**Comment by glima** [comment]
merging

**Pull request closed without merging**
