### PR TITLE
Add IO Convenience API, Platform API, Update API. Synchronize APIs.

### PR DESCRIPTION
**Pull request by zolkis**
Add specification for Platform and Update APIs.

Add an experimental IO API that uses the same style for all IO types (construct, configure, read, write, abort, onread, onerror). 

Other small changes coming from implementation feedback are synchronized here.

### CODE REVIEW

**Comment by zolkis** [comment]
For some strange reason, commits from previous PRs also appear here...
However, since these only affect the spec directory (doc/js-spec), I suggest merging.

**Comment by bdilly** [comment]
@zolkis please rebase your branch on top of the master branch.
A few conflicts will rise up.

Please consult our community contribution page in case of doubts:
https://github.com/solettaproject/soletta/wiki/Contributing#contributions-flow

Please do not merge this PR the way it is.

**Comment by zolkis** [comment]
I did rebase to my fork's master (and then I have solved the conflicts that still show up in the error log). I  didn't fetch the upstream master then, but did it now. There should be no conflicts, the build system still sees conflicts. Strange.

**Comment by bdilly** [comment]
OK @zolkis , thank you.
But it should be rebased on top of soletta's master branch, not yours.
The rationale is this way we avoid "merge commits" and keep our git history a bit cleaner.

**Comment by glima** [comment]
If you did fetch, please do it again, and assure that *origin/master* appear on your history (tig's output). That does not seem to be the case right now.

**Comment by bdilly** [comment]
These commits were rebased, had their conflicts solved and were merged via PR #2171 
Thanks

**Pull request closed without merging**
