### PR TITLE
Pinmux fixes

### PR DESCRIPTION
**Pull request by mbelluzzo**
Just minor bug fixes. This should close issue #147 as well.

### CODE REVIEW

**Comment by mbelluzzo** [comment]
@lucasdemarchi

**Comment by lucasdemarchi** [comment]
ACK. @thiagomacieira  ok now?

**Comment by barbieri** [comment]
+1

**Comment by thiagomacieira** [comment]
+1

**Comment by mbelluzzo** [comment]
Merging

**Pull request closed without merging**
