### PR TITLE
Fix make check fbp issues

### PR DESCRIPTION
**Pull request by tcanabrava**
A few issues where discovered by the reintroduction of the sanitize-address flag, and valgrind was behaving badly with a few tests, this patch series fixes that.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@tcanabrava suggestion since more than one person hit the same issue: when you know something is outdated or wrong, add a comment here in the PR so others don't spend time on it.

**Comment by cmarcelo** [comment]
Feel free to land the patches with +2, please create a new PR for the ones you had to fix.

**Comment by cmarcelo** [comment]
`#define land apply`

**Comment by tcanabrava** [comment]
newer version merged.

**Pull request closed without merging**
