### PR TITLE
Node.js bindings (v3)

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Replaces #1369

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
Hey! Could somebody please review this?

**Comment by poussa** [comment]
@cabelitos @barbieri @ceolin @ibriano PTAL. We'd like to get this merged. All the issues have been addressed.

**Comment by ibriano** [comment]
On Wed, 10 Feb 2016 23:52:45 -0800, Sakari Poussa wrote:
> @cabelitos @barbieri @ceolin @ibriano PTAL. We'd like to get this merged. All the issues have been addressed.

It was Carnaval here, so three days off and people are just coming back
to work now.

**Comment by ceolin** [comment]
not tested, but it seems to be ok. @cabelitos are you going to test it ?

**Comment by cabelitos** [comment]
@ceolin Me and @gabrielschulhof tested those patches, they are ok now :)

**Comment by cabelitos** [comment]
+1 for the whole series.

**Comment by ceolin** [comment]
nice, go ahead then !

**Comment by gabrielschulhof** [comment]
I've also modified the semaphore to make nvm, node, and npm work inside docker as of https://semaphoreci.com/solettaproject/soletta/branches/master/builds/523.

**Comment by gabrielschulhof** [comment]
Correction: https://semaphoreci.com/solettaproject/soletta/branches/master/builds/527

**Comment by bdilly** [comment]
seems good.
thanks for working on semaphore.

**Pull request closed without merging**
