### PR TITLE
Platform+Flow: Add locale API and nodes.

### PR DESCRIPTION
**Pull request by cabelitos**
Depends on #1164 

* Do not review  29ced30 here, check #1164

### CODE REVIEW

**Comment by cabelitos** [comment]
Strange, the sempahore is failing because it can't open /etc/locale.conf.
Does someone knows what distribution is the sempahore using it?

**Comment by barbieri** [comment]
an old one... not-systemd compatible.

It may be testing micro-linux, in that case I'd say do not fail, just WRN() and keep going without any file.

Of course you won't have write permission in any way to do the "set" tests of any of those platform issues, that's all right. The proper way to test would be to spawn a container or VM and test things in there (for micro-linux or systemd).

**Comment by cabelitos** [comment]
@barbieri The problem is that is not failing on a test, it is failing during platform startup (at sol_platform_init() ), because during the startup I read the conf file (/etc/locale.conf) and I make calls to setlocale() explicitly. If you can, please take a look at sol_platform_init()

Should I remove that code?

**Comment by barbieri** [comment]
no, just fail gently... WRN() and keep going, do not return -ENOENT

**Comment by cabelitos** [comment]
Sounds good.

**Comment by cabelitos** [comment]
Closing in favor of: #1172

**Pull request closed without merging**
