### PR TITLE
Make headers compatible with C++

### PR DESCRIPTION
**Pull request by ceolin**
- add necesary casts in glib-integration
- make sol-log (int-check) compatible with c++
- added target to test public headers with g++
- added missing stdbool include

### CODE REVIEW

**Comment by ceolin** [comment]
@thiagomacieira could you please take a look in https://github.com/solettaproject/soletta/commit/e47cf001ab7d704db2575b74d1cbeea0961e6451

I guess there are better solutions for this problem. I could not find something equivalent with `__builtin_choose_expr()` in c++.

**Comment by ceolin** [comment]
we can avoid the `__builtins_types_compatible()` but we still can't have the same implementation that C. `_SOL_TYPE_FORMAT` will be processed as the function `_sol_int_format()` and we will not be able to concat it in the macro.

We will still need get the result and concat with the other parameters using the stack.

Am I wrong ?

**Comment by vcgomes** [comment]
Yeah, I see the problem. I tried to come up with something, without success. @cmarcelo @thiagomacieira ideas?

**Comment by thiagomacieira** [comment]
I haven't had the time to look into this yet. Give me a day or two.

**Comment by ceolin** [comment]
don't worry, thank you for helping with it.

**Comment by thiagomacieira** [comment]
Added a few comments.

**Comment by ceolin** [comment]
committed with suggestions

**Pull request closed without merging**
