### PR TITLE
check: allow disabling colors [v2]

### PR DESCRIPTION
**Pull request by cmarcelo**
Replaces #239.

Changes from version 1:
- Use a single option modelled after git-diff and Leandro suggestion.
- Change `check-style.py` to work the same way.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@acidx @glima @dorileo

**Comment by lpereira** [comment]
Looks fine.

(Also, my username here is @lpereira.)

**Comment by glima** [comment]
Fine by me too.

**Comment by cmarcelo** [comment]
Applied in 0836aee613156756cd22f97b9986113b00a8051e and  97253a3bb65d84722cf0d1e1d793bf95eaa48dbf.

**Pull request closed without merging**
