### PR TITLE
flow: Update 7-seg node to use board labels

### PR DESCRIPTION
**Pull request by mbelluzzo**
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>

### CODE REVIEW

**Comment by bdilly** [comment]
@mbelluzzo don't you think it's required to have a "raw" option here as well?

**Comment by mbelluzzo** [comment]
Yep, I'm already adding that. Will push the fix soon.

**Comment by mbelluzzo** [comment]
Updated!

**Comment by bdilly** [comment]
:+1:

Btw, using a single raw options is a good idea. No reason to have granularity per pin.

I'll adopt the same approach in the ultrasonic sensor.

**Comment by mbelluzzo** [comment]
Merged, and btw build was already b0rked :-P

**Pull request closed without merging**
