### PR TITLE
support another 5 category sensors into soletta iio node

### PR DESCRIPTION
**Pull request by guchaojie**
This PR supports Magnet , Pressure, Color , Huminity and Accelerate Category into iio node. And all the sensor category have been tested to work well in minnowmax using different sensors supported by their iio drivers.

### CODE REVIEW

**Comment by guchaojie** [comment]
@edersondisouza This PR is focus on extending sensor category support list  in soletta for QA test. Next step we will optimize the source code such as factoring out common code as your suggestion

**Comment by guchaojie** [comment]
@bdilly Anyone can have a review this PR? Any comment is welcome.

**Comment by barbieri** [comment]
sorry, both @bdilly and @edersondisouza are on vacation :-(

the patches looks good, keep going with other patches and they will review as soon as they are back.

**Comment by edersondisouza** [comment]
I'm OK with factoring out common code on a future patch, but wouldn't do it before simplify the others patches?

**Comment by guchaojie** [comment]
@edersondisouza yes, our plan is to extending sensor category to support 30 sensors before M3. In case to avoid introducing bugs in this process , so we factoring out common in next patch. That would make easy to maintain the code step by step.

**Pull request closed without merging**
