### PR TITLE
Openssl

### PR DESCRIPTION
**Pull request by glima**
Bring make check back to life on current distros. make check-valgrind is b0rked for test-mainloop-linux, gotta figure out why now.

### CODE REVIEW

**Comment by glima** [comment]
@sergiomb2 is it you that pinged about this and the spec bump?

**Comment by sergiomb2** [comment]
I pinged for update solleta in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1424460 , as I wrote Fedora 26  have openssl-1.0 as compat package and openssl-1.1 as the main package , so migrate to openssl 1.1 is not required

**Comment by sergiomb2** [comment]
Add this patch [2] fixes build for F26 
F27 fails to build on new curl according my build in [1]

[1] 
https://copr.fedorainfracloud.org/coprs/sergiomb/builds_for_Stable_Releases/build/658499/
[2]
[soletta.spec.patch.txt](https://github.com/solettaproject/soletta/files/1447147/soletta.spec.patch.txt)

**Comment by glima** [comment]
Thanks, @sergiomb2 . Will take a look at the curl issue as soon as I can (and test/apply the other patch).

**Comment by sergiomb2** [comment]
Anyway I don't see any openssl package in Fedora

**Comment by sergiomb2** [comment]
[soletta.spec.patch.v2.txt](https://github.com/solettaproject/soletta/files/1447447/soletta.spec.patch.v2.txt)
Soletta 2 builds on F25 and F26 but stil fails on F27 with curl

**Comment by glima** [comment]
@sergiomb2 thanks for the python2 requires thing. I'm not sure yet when we need it, but will test/incur with it soon. I know the builds may pass (why do send patches against an old spec, BTW? I have a more up to date in this very same repo), but I'm not talking x86 builds, but the alien architectures that fail. We *have* to address those too, plus the curl thing.

**Comment by sergiomb2** [comment]
I'm using the latest spec (in Fedora) [1] 
[1]
https://src.fedoraproject.org/rpms/soletta/blob/master/f/soletta.spec
https://src.fedoraproject.org/cgit/rpms/soletta.git/tree/soletta.spec

**Comment by glima** [comment]
make: *** [tools/build/Makefile.rules:377: build/stage/lib/comms/sol-http-client-impl-curl.o] Error 1

was seen on logs now, indeed. Will attack this as soon as I got time.

BTW, @ceolin care to look at the patch, when you can, please?

**Comment by sergiomb2** [comment]
F27 have one  curl update [1] which breaks the build 

[1] 
 https://apps.fedoraproject.org/packages/libcurl

**Comment by glima** [comment]
Timeout. Merging this.

**Pull request merged**
