### PR TITLE
tools/run-fbp-tests: support python 2 and 3

### PR DESCRIPTION
**Pull request by bdilly**
With a few changes and imports it seems to be working fine.

Signed-off-by: Bruno Dilly <bruno.dilly@intel.com>

### CODE REVIEW

**Comment by anselmolsm** [comment]
@bdilly interesting, I didn't know about it.
But, what about the line 1 which refers to python3?

**Comment by cmarcelo** [comment]
+1

Probably we should refer to "#!/usr/bin/env python" only?

**Comment by anselmolsm** [comment]
@cmarcelo yep, this should work, I think.

**Comment by bdilly** [comment]
@cmarcelo @anselmolsm you're right.
change done
merged

**Pull request closed without merging**
