### PR TITLE
sol-vector: Update functions documentation with their corresponding time complexities

### PR DESCRIPTION
**Pull request by kaspersky**
Signed-off-by: Vladimir Cernov <cernov.vladimir@gmail.com>

### CODE REVIEW

**Comment by bdilly** [comment]
Hi @kaspersky , really nice to see your first contribution =)

Not sure if you're familiarized with our CI system yet.
It makes lot of checks, including coding style ->  https://semaphoreci.com/solettaproject/soletta/branches/pull-request-1571/builds/1

In your case, you can just disregards - it's a false positive. It's comparing to code blocks you didn't touch.

Also I would like to suggest you to check the following page if you didn't yet:
 * https://github.com/solettaproject/soletta/wiki/Contributing#contributions-flow

**Comment by kaspersky** [comment]
Hi Bruno, I checked the pull request instructions, did I miss a step?

**Comment by bdilly** [comment]
No, you're good.

**Comment by otaviobp** [comment]
merged.

**Pull request closed without merging**
