### PR TITLE
iio: Add support to read processed channels

### PR DESCRIPTION
**Pull request by edersondisouza**
Some devices expose IIO channels that are already processed, so it's not
necessary to apply offset and scale on them. Such channels have the
suffix '_input', instead of '_raw' of the raw ones. Now, Soletta IIO
module should be able to read them - it'll first to open the raw one and
them the processed one. In this order because '_raw' ones are way more
common.
This change is internal only and does not affect current API - it should
be transparent to API user which kind of channel is being used.

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

### CODE REVIEW

**Comment by edersondisouza** [comment]
@guchaojie Could you please test this? I cannot test this patch since I don't have a device to exercise this case. Please, check if nothing breaks on working devices, and if the device that uses '_input' works. Also, test it with buffer enabled and disabled, and check if all readings makes sense. If there's something wrong, you can base on this patch and send a new PR fixing it, as I can't test it.

**Comment by guchaojie** [comment]
OK, I was on annual leave last few days. I will test it today

**Comment by yongli3** [comment]
@guchaojie @edersondisouza I tested this change using Galileo board + TSL2563 light sensor + Chaojie’s light node patch

The TSL2563 does not support buffer enable feature, so I cannot test the “buffer enable” cases

By modifying the channel name in “ADD_CHANNEL”, I can read the data from 
both /sys/bus/iio/devices/iio:device1/in_intensity_both_raw and /sys/bus/iio/devices/iio:device1/in_illuminance0_input

WRN: ./src/lib/io/sol-iio.c:1059 sol_iio_read_channel_value() processed=0 buffer_enable=0
WRN: ./src/lib/io/sol-iio.c:1074 sol_iio_read_channel_value() path=/sys/bus/iio/devices/iio:device1/in_intensity_both_raw
#anon:40:34 6514.000000 (float range)
WRN: ./src/lib/io/sol-iio.c:1059 sol_iio_read_channel_value() processed=0 buffer_enable=0
WRN: ./src/lib/io/sol-iio.c:1074 sol_iio_read_channel_value() path=/sys/bus/iio/devices/iio:device1/in_intensity_both_raw
#anon:40:34 6492.000000 (float range)

WRN: ./src/lib/io/sol-iio.c:1059 sol_iio_read_channel_value() processed=1 buffer_enable=0
WRN: ./src/lib/io/sol-iio.c:1074 sol_iio_read_channel_value() path=/sys/bus/iio/devices/iio:device1/in_illuminance0_input
#anon:40:34 156.000000 (float range)
WRN: ./src/lib/io/sol-iio.c:1059 sol_iio_read_channel_value() processed=1 buffer_enable=0
WRN: ./src/lib/io/sol-iio.c:1074 sol_iio_read_channel_value() path=/sys/bus/iio/devices/iio:device1/in_illuminance0_input
#anon:40:34 155.000000 (float range)

SYSFS nodes list:
root@intel-quark:/sys/bus/i2c/devices/0-0039/iio:device1# ls -l
total 0
-r--r--r-- 1 root root 4096 Jan 28 03:25 dev
drwxr-xr-x 2 root root    0 Jan 28 03:25 events
-rw-r--r-- 1 root root 4096 Jan 28 03:25 in_illuminance0_input
-rw-r--r-- 1 root root 4096 Jan 28 03:25 in_intensity_both_calibscale
-rw-r--r-- 1 root root 4096 Jan 28 03:25 in_intensity_both_raw
-rw-r--r-- 1 root root 4096 Jan 28 03:25 in_intensity_ir_calibscale
-rw-r--r-- 1 root root 4096 Jan 28 03:25 in_intensity_ir_raw
-r--r--r-- 1 root root 4096 Jan 28 03:25 name
drwxr-xr-x 2 root root    0 Jan 28 03:25 power
lrwxrwxrwx 1 root root    0 Jan 28 03:25 subsystem -> ../../../../../../../bus/iio
-rw-r--r-- 1 root root 4096 Jan 28 03:25 uevent
root@intel-quark:/sys/bus/i2c/devices/0-0039/iio:device1#
root@intel-quark:/sys/bus/i2c/devices/0-0039/iio:device1# cat name
tsl2563

**Comment by edersondisouza** [comment]
Hi @yongli3,

So, I can conclude that this PR is working fine?

**Comment by yongli3** [comment]
yes I think we can merge it

�� 2016��2��1����19:29��Ederson de Souza <notifications@github.com<mailto:notifications@github.com>> ������


Hi @yongli3<https://github.com/yongli3>,

So, I can conclude that this PR is working fine?

��

**Comment by edersondisouza** [comment]
Integrated. Tks!

**Pull request closed without merging**
