### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by ceolin**
- codespell
- http-server functions link

### CODE REVIEW

**Comment by barbieri** [comment]
Codespell? Really?! Trying to cheat commit lines?

@lucasdemarchi

**Comment by lucasdemarchi** [comment]
YAY!!! You all make jokes but in the end is an useful tool. @ceolin congrats, just added you as maintainer of codespell as well.

**Comment by mbelluzzo** [comment]
Github needs a like button! Loled hard at "maintainer"

**Comment by ceolin** [comment]
holiday commits !!!

**Comment by edersondisouza** [comment]
+1

**Pull request closed without merging**
