### PR TITLE
mqtt: Gives user data in config

### PR DESCRIPTION
**Pull request by ceolin**
It is the same pattern used by message digest.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
from v1:
 - Host and port in the config
 - store the user data as const pointer

**Comment by vcgomes** [comment]
Looks good.

**Comment by glima** [comment]
:+1:

**Comment by cabelitos** [comment]
looks goodd

**Pull request closed without merging**
