### PR TITLE
Fixes v2

### PR DESCRIPTION
**Pull request by ceolin**
-v2
 - Removed duplicated commit (there already is a commit fixing the exit() problem)

This series fix the issues:
* https://github.com/solettaproject/soletta/issues/97
* https://github.com/solettaproject/soletta/issues/89

@lpereira I prefer to put the information about the issues in the pullreq message instead of the put in the commit messages.

### CODE REVIEW

**Comment by lpereira** [comment]
The issues will be closed automatically if they're in commit messages. The messages in the PR will only work if it's merged via the GitHub UI, but we decided to fight the tool we're using rather than just embrace it... :P

**Comment by ceolin** [comment]
I do prefer not mess our history with github's information :)

Anyway, about the commits do I have your ack ?

**Comment by ceolin** [comment]
That is exactly the point, when i2c-dev.h is given by i2c-tools it is defined on i2c-dev.
T

**Comment by barbieri** [comment]
+1

**Comment by ceolin** [comment]
merged, thanks

**Pull request closed without merging**
