### PR TITLE
Enable Soletta to run on Zephyr's nanokernel

### PR DESCRIPTION
**Pull request by ibriano**
Also implement mainloop locks and wake it up when idler/timer are added from
other threads.

### CODE REVIEW

**Comment by edersondisouza** [comment]
looks ok

**Comment by vcgomes** [comment]
Apart from the minor comment. Looking good. :+1:

**Comment by glima** [comment]
OK for me as well.

**Comment by ibriano** [comment]
Merged with vcgomes' comment fixed and a new commit fixing a pretty serious compiler warning that's entirely unrelated to this series but I couldn't just ignore.

**Pull request closed without merging**
