### PR TITLE
Make sanitize depend on Linux

### PR DESCRIPTION
**Pull request by zehortigoza**
To this feature works on RIOT and Contiki we should add the sanitize
compiler flags when the OS build system is generating the final binary
contaning the OS + Soletta + application.
Until we don't have some infrascructure to get the compiler flags that
Solleta need we will keep it disabled.

### CODE REVIEW

**Comment by cmarcelo** [comment]
+1

@dorileo @ibriano could either of you take a look?

**Comment by ibriano** [comment]
Does the job

**Comment by cmarcelo** [comment]
Minor: last sentence of the commit message is a bit confusing. It's not even clear to me we want those sanitizers in RIOT / Contiki.

**Comment by cmarcelo** [comment]
They add runtime checks. We probably want to disable them in the small targets.

**Comment by dorileo** [comment]
LGTM.

**Comment by dorileo** [comment]
@cmarcelo it doesn't make sense to disable dep-resolver tests on a given condition (be it a platform, os or whatever) the dep-resolver runs before the configuration selection, i.e when you run make menuconfig in a fresh cloned tree the dep-resolver will be run before launching the menuconfig to generate the dep-resolver's cache. I don't think we're saving too much by avoiding some tests.

**Comment by cmarcelo** [comment]
@dorileo I meant, if I get this right, we'll never enable FEATURE_CC_SANITIZE, even if we manage to separate the build flags on small os side. Just the commit message seems confusing. "Runtime checks" was refering to what the sanitizer does.

Suggestion:

> Contiki and RIOT builds don't fully support this and we probably won't need these extra runtime checks that sanitizer adds to the code for those targets.

**Comment by zehortigoza** [comment]
Merged with cmarcelo message commit.

**Pull request closed without merging**
