### PR TITLE
Include sol-flow-buildopts.h to the exported headers

### PR DESCRIPTION
**Pull request by zehortigoza**
Signed-off-by: José Roberto de Souza <jose.souza@intel.com>

### CODE REVIEW

**Comment by vcgomes** [comment]
@bdilly is working on a series that will fix this problem and few related ones. Would you mind waiting a little and see if his PR solves your problems?

**Comment by dorileo** [comment]
-1 @bdilly and @glima  as far as I know are re-designing this headers stuffs...

**Comment by vcgomes** [comment]
@zehortigoza #173 was just merged, it should solve your problem.

**Comment by dorileo** [comment]
this pull request overlaps with dilly's patch https://github.com/solettaproject/soletta/commit/05f7fd2a339f318c64b3830d85e134d8429ee254

since it's in already, I'm closing this one.

**Comment by zehortigoza** [comment]
Yes, it fixed thanks.

**Pull request closed without merging**
