### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by bdilly**
closes gh-1994

### CODE REVIEW

**Comment by glima** [comment]
All good for me. Just wait for CI

**Comment by edersondisouza** [comment]
I could not build this patch with flow disabled:
./build/stage/lib/common/sol-types.o: In function `sol_drange_mod':
sol-types.c:(.text.sol_drange_mod+0x48): undefined reference to `fmod'
./build/stage/shared/sol-util.o: In function `sol_util_double_equal':
sol-util.c:(.text.sol_util_double_equal+0x8d): undefined reference to `fmin'
collect2: error: ld returned 1 exit status
tools/build/Makefile.rules:394: recipe for target 'build/soletta_sysroot/usr/lib/libsoletta.so' failed
make: *** [build/soletta_sysroot/usr/lib/libsoletta.so] Error 1
Please, look at https://github.com/solettaproject/soletta/pull/1996/commits/64ac7ea3f07d3a26a3d264869f28dc376ba64cc9 (rogue commit to fix build that I've written when testing IPM, I wasn't aware of https://github.com/solettaproject/soletta/issues/1994)

**Comment by barbieri** [comment]
@edersondisouza make clean/git clean?

**Comment by edersondisouza** [comment]
On 09-05-2016 15:58, Gustavo Sverzut Barbieri wrote:
> @edersondisouza <https://github.com/edersondisouza> make clean/git clean?

I'm always using make distclean, not better.

**Comment by bdilly** [comment]
fine, I wasn't able to reproduce this issue with the ldflag, but I'm cherry-picking your commit and let's see if it's ok now. Waiting for CI to run all tests...

**Comment by edersondisouza** [comment]
On 09-05-2016 16:20, Bruno Dilly wrote:
> fine, I wasn't able to reproduce this issue with the ldflag, but I'm
> cherry-picking your commit and let's see if it's ok now. Waiting for CI
> to run all tests...

Worked here, tks! But weird that you couldn't reproduce it...

**Pull request merged**
