### PR TITLE
Util export functions used on samples

### PR DESCRIPTION
**Pull request by ceolin**
- Export sol-util.h
 - Fix samples to not use internal headers
 - Add doc

### CODE REVIEW

**Comment by barbieri** [comment]
-1 export it all :-)

from the remaining, now `sol-util-internal.h` just couple of macros are missing prefix, so just add to those. No need to always use `sol_util_`, such as in `sol_streq()` is enough, no need to bloat to `sol_util_streq()`.

**Comment by glima** [comment]
You don't seem to install the header too

**Comment by glima** [comment]
Now I see it, disregard

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/pull/1298

**Pull request closed without merging**
