### PR TITLE
Persistence test

### PR DESCRIPTION
**Pull request by edersondisouza**
It should help debugging persistence. More information on logs and a way to establish dependency between fbp tests.

### CODE REVIEW

**Comment by otaviobp** [comment]
lgtm

**Comment by barbieri** [comment]
+1, however persistence is critical and I think we should add forced tests in plain C to control all failure cases, like exit (sol_quit) before timeouts fire, replace of writes, interleaved writes and reads, particularly reads before write commit to disc.

**Comment by edersondisouza** [comment]
Async PR does have C API testing that can be improved on future.

**Comment by edersondisouza** [comment]
Integrated.

**Pull request closed without merging**
