### PR TITLE
Node.js bindings: Add infrastructure and start binding platform functions (v2)

### PR DESCRIPTION
**Pull request by gabrielschulhof**
This PR replaces #1233

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
Ummm, what is ```__asan_unregister_globals``` and why is soletta using it :)

**Comment by gabrielschulhof** [comment]
https://www.google.fi/search?q=__asan_unregister_globals brings up some interesting pages ...

**Comment by gabrielschulhof** [comment]
https://github.com/google/sanitizers/issues/380 is interesting. Perhaps this is issue arises from the fact that soletta.node is built with g++ whereas soletta.so is built with gcc.

**Comment by ceolin** [comment]
It's libasan thing. You can enable/disable this address sanitizer in the menuconfig

basic -> compiler options -> compiler sanitize

It's useful to detect uninitialized reads and memory leaks

**Comment by gabrielschulhof** [comment]
@ceolin so, does this mean it needs to be ```apt-get install```-ed on the semaphore?

**Comment by gabrielschulhof** [comment]
@ceolin is libasan getting loaded dynamically? If so, it may be running into the same issue as https://github.com/solettaproject/soletta/issues/1331

**Comment by ceolin** [comment]
i think it's dynamic. I am seeing what can be happening

**Comment by gabrielschulhof** [comment]
Maybe we should have a test where we load soletta with ```RTLD_LOCAL | RTLD_NOW``` - which is what happens when soletta is loaded from another library, to make sure that chaining works. Of course, this still wouldn't catch issues like #1331 ... hmmm ...

**Comment by gabrielschulhof** [comment]
What if we make use of libasan only when building in debug mode?

**Comment by ibriano** [comment]
On Fri, 29 Jan 2016 08:29:28 -0800, gabrielschulhof wrote:
> What if we make use of libasan only when building in debug mode?
> 

That's already the case, IIRC.

**Comment by ceolin** [comment]
i've made a pull request passing -z,defs to linker. This should check if there are undefined symbols.

**Comment by gabrielschulhof** [comment]
OK, I'll wait for that to land, then I'll rebase onto it and hopefully this issue will no longer be present.

**Comment by cabelitos** [comment]
@gabrielschulhof Could you please rebase with the master branch and try again?
Thank you

**Comment by cabelitos** [comment]
@gabrielschulhof You need to add to depedency check if the user have npm installed. I tried to run your branch and the build broke because I did not have npm.

**Comment by gabrielschulhof** [comment]
@cabelitos you have node but you don't have npm? I have a check for node, and node always comes with npm.

**Comment by cabelitos** [comment]
+1

**Pull request closed without merging**
