### PR TITLE
Convert script that run FBP from bash to Python

### PR DESCRIPTION
**Pull request by cmarcelo**
It's already better than the bash version and will make easier to make further changes.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@lpereira @bdilly I suspect converting to Python might make easy to implement the flexible expected lines you suggested in the other PR.

**Comment by bdilly** [comment]
@cmarcelo I agree. +1 with a minor comment.
I didn't test it.

**Comment by cmarcelo** [comment]
Changed the code to use more idiomatic check. Applied in 19ecbd0095d0a8a29db71e51fa2e3f8e747a6c4f and parent.

**Comment by lpereira** [comment]
:+1: for using Python instead of shell. A lot more readable.

**Pull request closed without merging**
