### PR TITLE
Build random fixes

### PR DESCRIPTION
**Pull request by dorileo**

### CODE REVIEW

**Comment by ulissesf** [comment]
+1, but remove 2nd patch since I moved PTHREAD and also changed to depend on HAVE_PTHREAD && SOL_PLATFORM_LINUX.

**Comment by tcanabrava** [comment]
-1 , still doesn't fix the issue.

**Comment by glima** [comment]
+1 modulo the 2nd patch

**Comment by dorileo** [comment]
applied...

**Pull request closed without merging**
