### PR TITLE
.gitignore: Add files moved to repo root as part of npm install

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Signed-off-by: Gabriel Schulhof <gabriel.schulhof@intel.com>

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@otaviobp PTAL

**Comment by ceolin** [comment]
this is ok, but why those files are not generated under the `build` directory ? whether `stage` or `soletta_sysroot`

**Comment by gabrielschulhof** [comment]
@ceolin the build process is designed such that, if node.js bindings are enabled, then at the end of ```make``` the soletta repo is a perfectly well-formed and installed npm package in addition to having a copy of the perfectly well-formed npm package under ```build/soletta_sysroot/<prefix>/lib/node_modules/soletta``` for the purposes of a possible subsequent ```make install```. So, if we want to support writing ```require( "soletta/uart" );``` or ```require( "soletta/gpio" );``` then the files ```uart.js``` resp. ```gpio.js``` have to reside in the repo root at the end of the build process, because npm packages do not have a ```make install``` step. They are built in their final resting place.

**Comment by otaviobp** [comment]
+1, if there isn't really a way of generating those files in build directory.

**Pull request closed without merging**
