### PR TITLE
sol-conffile: If find an error on JSON, log it as SOL_ERR

### PR DESCRIPTION
**Pull request by edersondisouza**
So the message is more visible to user, and not buried along lots of
other debug messages.

Signed-off-by: Ederson de Souza <ederson.desouza@intel.com>

### CODE REVIEW

**Comment by mbelluzzo** [comment]
+2

**Comment by barbieri** [comment]
not ERR, WRN. We use WRN in our stuff, not error... no big deal, that's the convention... error and critical are not being used in our side.

WRN is the default visibility, so will have the same effect

**Comment by edersondisouza** [comment]
I didn't get the part of 'our stuff' - isn't the conffile json given to us by users?

**Comment by barbieri** [comment]
our code

**Comment by edersondisouza** [comment]
Integrated with SOL_WRN. Tks!

**Comment by mbelluzzo** [comment]
What is the point to just wrn and keep going in those cases?

**Pull request closed without merging**
