### PR TITLE
coap: Safety check on public API

### PR DESCRIPTION
**Pull request by ceolin**
Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by ibriano** [comment]
Ok, I guess

**Comment by cabelitos** [comment]
+1

**Comment by glima** [comment]
I also vote for doing it on all those @ sol-coap.c.

**Comment by cabelitos** [comment]
me too

**Comment by ceolin** [comment]
@glima @cabelitos  please take a look in https://github.com/solettaproject/soletta/pull/1589

**Pull request closed without merging**
