### PR TITLE
Add test for the json parser

### PR DESCRIPTION
**Pull request by tcanabrava**
Simple test that makes sure all tokens are read in the correct
order.

Signed-off-by: Tomaz Canabrava <tomaz.canabrava@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
tcanabrava what is the status of this pullreq ? Do you agree with the comments ? Will you update the pullreq ?

**Comment by tcanabrava** [comment]
Was busy on other things, closing pull req and merging it.

**Comment by mbelluzzo** [comment]
@tcanabrava is this in? If not, plz do it and close the PR.

;-)

**Comment by lpereira** [comment]
Minor, but before merging, please change the commit message to read `JSON scanner` or `JSON lexer`. This is not a parser.

**Comment by tcanabrava** [comment]
lpereira - sorry, I had commited before reading your comment. =/

**Comment by tcanabrava** [comment]
@mbelluzzo  I waited for the KConfig buildsystem change before commiting.

**Pull request closed without merging**
