### PR TITLE
flow: remove unused forward declaration

### PR DESCRIPTION
**Pull request by cmarcelo**
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

### CODE REVIEW

**Comment by cmarcelo** [comment]
I couldn't understand whether semaphoreci is having a problem or my patch, the error I've found in https://semaphoreci.com/solettaproject/soletta/branches/pull-request-2250/builds/1 seems related to some git stuff that happens in sema.

**Comment by cabelitos** [comment]
I forced a rebuilt. Sometimes these things happen.

**Comment by cabelitos** [comment]
+1 btw

**Comment by bdilly** [comment]
@cabelitos couldn't you please write an email to them notifying about this issue? Is it some kind of conflict between the two threads?

**Comment by bdilly** [comment]
:+1:

**Comment by cmarcelo** [comment]
Applied in 45868f001a897f9e2b51b04420ef3dd9ae7d59fb.

**Pull request closed without merging**
