### PR TITLE
More array ports

### PR DESCRIPTION
**Pull request by lgywata**
More changes to array ports schema: Float and Int types.

### CODE REVIEW

**Comment by lgywata** [comment]
@barbieri suggested it and @cmarcelo also mentioned the 32 array ports for operations like addition, multiplication, etc. I sent an email to the list about this saying that I would proceed with the changes if no one else had a different opinion. But, yes, I agree the 32 is arbitrary, but If I'm a Soletta user I'd prefer the 32 ports instead of having to cascade several nodes to have a simple arithmetic operation done. Besides, we can get back here in the future and change it again when dynamic arrays is supported.

**Comment by ibriano** [comment]
It was discussed in the devapp mailing list, which brings up the

**Comment by ibriano** [comment]
It was brought up in the devapp-list, which brings up the soletta-dev that we should be using for these things (unless it's something that can't be discussed in public).
32 is arbitrary, but seems large enough to be sufficient for now. About dynamic array ports, are people seeing a need to have that in the near future? It would require some major reworking of the way we do things right now.

**Comment by anselmolsm** [comment]
@lgywata I see that you updated the tests, remember to also check the samples affected by these changes.

**Comment by lgywata** [comment]
@anselmolsm, you're right. Thanks!

**Comment by lgywata** [comment]
v2 sent with samples included. #220

**Pull request closed without merging**
