### PR TITLE
misc: Fix typos

### PR DESCRIPTION
**Pull request by ricardotk**
This patch fixes general typos

### CODE REVIEW

**Comment by bdilly** [comment]
A couple issues raised by semaphoreci.
One of them I suppose will be fixed by #2277 
Maybe the other one was just a timeout issue? It seems the case but I would suggest you to rebase on top of master after I merge my PR and we see if it's gone.

**Comment by ricardotk** [comment]
@bdilly Mmm, I rebased my branch and pushed, but its failing on "License, style and docs" step. Any ideas?

**Comment by ricardotk** [comment]
It worked :dancers:

**Comment by bdilly** [comment]
nice.
anyway, these issues related to coding style on not touched parts of the code can be ignored.

**Pull request merged**
