### PR TITLE
Fix build: detect memrchr and strdupa

### PR DESCRIPTION
**Pull request by thiagomacieira**
These two functions are GNU libc extensions.

### CODE REVIEW

**Comment by thiagomacieira** [comment]
Cannot reproduce the test failure.

**Comment by barbieri** [comment]
the failure is stupid uncrustify (check-style). We cannot get it to consider only the fragments that changed and it's checking code that was already there... so ignore and merge anyway.

**Comment by barbieri** [comment]
actually one small part of the style check is related to your change, better fix it: https://semaphoreci.com/solettaproject/soletta/branches/pull-request-1336/builds/1

```
-    for ( ; ptr != haystack; --ptr) {
+
+    for (; ptr != haystack; --ptr) {
```

That is, should be no space between `(` and `;`. And the coding style requires one empty line between variable declaration and the code.

**Comment by thiagomacieira** [comment]
I would have thought that having the ; isolated would make it more noticeable, but sure.

**Comment by thiagomacieira** [comment]
False positive on CI.

**Comment by thiagomacieira** [comment]
ping

**Comment by barbieri** [comment]
+1

**Pull request closed without merging**
