### PR TITLE
Symbols - Fix unresolved symbols

### PR DESCRIPTION
**Pull request by ceolin**

### CODE REVIEW

**Comment by barbieri** [comment]
+0, but check the linker flags is okay with @thiagomacieira as he ports to MacOS and our semaphore still doesn't cover it.

Also, semaphore says `flow/http-client` also misses it

**Comment by ceolin** [comment]
it was complaining with http-server that i've added. I've asked iscaro to test and also worked in his system. I'm checking what is wrong

**Comment by ceolin** [comment]
i know that this is a linker flag, but adding it to `COMMON_LDFLAGS` simply did not work.
probably there is another problem. I'll check before add it and see why it's failing on semaphore

**Comment by thiagomacieira** [comment]
If you pass an -l flag while -c is active, some compilers will complain about arguments not used because no linking was done. Please make sure that the -l flag is passed only to the linking step.

**Comment by ceolin** [comment]
i'll, thanks !

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/pull/1372

**Pull request closed without merging**
