### PR TITLE
samples: fix uninitialized variable warning

### PR DESCRIPTION
**Pull request by kaspersky**
Signed-off-by: Vladimir Cernov <cernov.vladimir@gmail.com>

@cabelitos You should be responsible for reviewing and merging this one :)

### CODE REVIEW

**Comment by cabelitos** [comment]
@kaspersky +1
I really don't why gcc did not complain to me... :/
Anyway @otaviobp did the same fix in https://github.com/solettaproject/soletta/pull/2066

**Comment by cabelitos** [comment]
I guess GCC hates me

**Comment by otaviobp** [comment]
My bad. You did it first. I'll close mine

**Comment by otaviobp** [comment]
merged

**Pull request closed without merging**
