### PR TITLE
misc: Fix typo

### PR DESCRIPTION
**Pull request by ricardotk**
Signed-off-by: Ricardo de Almeida Gonzaga <ricardo.gonzaga@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
have you catch it using codespell ? if not, please use it to get all typos once please.

**Comment by ricardotk** [comment]
Yes, I did it. Its the only typo, the other ones are in third party code

**Comment by ceolin** [comment]
Please, go ahead  +2

**Comment by ricardotk** [comment]
merged, thanks! :v:

**Pull request closed without merging**
