### PR TITLE
build: Respect the CC variable from the environment

### PR DESCRIPTION
**Pull request by vcgomes**
This patch is necessary for using clang scan-build with Soletta, as it
works by forcing the compiler pointed by the CC variable to be one its
analyzer.

Signed-off-by: Vinicius Costa Gomes <vinicius.gomes@intel.com>

### CODE REVIEW

**Comment by barbieri** [comment]
-1

this is troublesome, people will do mistakes. The proper solution is to define TARGETCC or HOSTCC

**Comment by vcgomes** [comment]
I don't think that I understand. Anyway, see if this version is better.

btw, my idea with this is at least to have what is needed to run `scan-build` in Soletta, I don't care specially if this is not applied.

**Comment by barbieri** [comment]
this one is better

**Comment by barbieri** [comment]
+1

**Comment by vcgomes** [comment]
Pushed with a minor fix in the commit message. Thanks

**Pull request closed without merging**
