### PR TITLE
generator: Use the right type name for float options

### PR DESCRIPTION
**Pull request by ibriano**
Since the option type is float, not double, the generator was not
properly producing the options initialization for each field, resulting
in a considerable amount of warnings when running make check-fbp-bin

### CODE REVIEW

**Comment by lpereira** [comment]
:+1:

**Comment by ibriano** [comment]
Added a few more commits to fix check-bin-fbp when running with allmodconfig

**Comment by bdilly** [comment]
series lgtm

**Comment by ibriano** [comment]
Merged

**Pull request closed without merging**
