### PR TITLE
More fbp-generator changes

### PR DESCRIPTION
**Pull request by cmarcelo**
A bunch of small changes (some accidental, some that were in my TODO for this code): minor bug fixes, some feature improvements and some refactoring.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@vcgomes @ricardotk

**Comment by cmarcelo** [comment]
In particular, the patch that moves from using temporary files to using a buffer in memory deserve a careful review.

**Comment by vcgomes** [comment]
Apart from these minor comments, series looks good.

**Comment by cmarcelo** [comment]
Applied in baaf18d54eaf84f31f1f0c010da9e48b3c8f3ebb.

**Pull request closed without merging**
