### PR TITLE
String replace

### PR DESCRIPTION
**Pull request by glima**
changes since v1:

 * sol_util_ssize_mul() fixed for compilers without the builtin overflow calculation
 * some typos pointed out by @dorileo fixed on the next commit

### CODE REVIEW

**Comment by glima** [comment]
Sorry :( I'll check if I can convert at least some of the macros. The differences of the use cases is what sucks.

**Comment by glima** [comment]
@edersondisouza , I meant I'll do that later. Is it ok to get in as is, for now?

**Comment by edersondisouza** [comment]
On 13-08-2015 15:11, Gustavo Lima Chaves wrote:
> @edersondisouza <https://github.com/edersondisouza> , I meant I'll do
> that later. Is it ok to get in as is, for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solettaproject/soletta/pull/521#issuecomment-130784555>.
>
Yep (hope no new coverity issues =D).

**Comment by glima** [comment]
Cool, merging :)

**Pull request closed without merging**
