### PR TITLE
Fixes: starting effort to make the package live again on Fedora

### PR DESCRIPTION
**Pull request by glima**

### CODE REVIEW

**Comment by edersondisouza** [comment]
`make check-valgrind` fails on `test-mainloop-linux` here. Is it expected? 
Did you check semaphore complaints?

**Comment by glima** [comment]
Yes, this is new. It seems to me like a false positive, what do you think? I'm not too much alarmed with that because check-valgrind is not run on Fedora specs.

**Comment by glima** [comment]
@edersondisouza ping?

**Comment by edersondisouza** [comment]
:+1:

**Pull request merged**
