### PR TITLE
Utils improvement

### PR DESCRIPTION
**Pull request by ceolin**
- Missing SOL_API
 - Exporting ARRAY_SIZE (SOL_UTIL_ARRAY_SIZE)

### CODE REVIEW

**Comment by ceolin** [comment]
@cabelitos

**Comment by cabelitos** [comment]
Looks good, However check the semaphore errors before merging.

**Comment by ceolin** [comment]
they are all check-style issues (not introduced in these commits)

**Comment by ceolin** [comment]
thanks for review it

**Pull request closed without merging**
