### PR TITLE
build: Fix buildopts platform detection

### PR DESCRIPTION
**Pull request by ceolin**
Fix platform linux detection

### CODE REVIEW

**Comment by lpereira** [comment]
Rubberstamping: :+1:

**Comment by lpereira** [comment]
BTW, isn't there anything similar to Perl's `use strict`?

**Comment by ceolin** [comment]
Have no idea, for C's code we can pass the flag "-Werror=undef" and the build will fail if we do "#if bogus" and "bogus" is not defined.

**Comment by ceolin** [comment]
merged, thanks!

**Pull request closed without merging**
