### PR TITLE
datatypes/vector: fix memset arithmetics [v2]

### PR DESCRIPTION
**Pull request by bdilly**
changelog:
  * added changes suggested by @cmarcelo regarding checks
  of overflow on grow()

Issue reported by coverity:

Suspicious implicit sign extension: "n" with type "unsigned short"
(16 bits, unsigned) is promoted in "v->elem_size * n" to type "int"
(32 bits, signed), then sign-extended to type "unsigned long" (64 bits,
unsigned). If "v->elem_size * n" is greater than 0x7FFFFFFF, the
upper bits of the result will all be 1.

Signed-off-by: Bruno Dilly <bruno.dilly@intel.com>

### CODE REVIEW

**Comment by barbieri** [comment]
@edersondisouza is right, use that function.

**Comment by cmarcelo** [comment]
+1 with ederson suggestion.

**Comment by bdilly** [comment]
I wasn't aware of this function. Perfect
Thanks

**Comment by barbieri** [comment]
hum.. actually, reading this code and the coverity message I wonder why `uint16_t * uint16_t` is promoted to signed integer, that's the case if it says `v->elem_size * n` is promoted to integer.

Actually, given both are `uint16_t` they shouldn't overflow even if `sizeof(size_t) == sizeof(uint32_t)` (32 bits machine). I guess this warning is kinda moot, maybe we just need to adapt the types before doing the multiplication to `uint32_t` (or `size_t`) before doing the multiplication and no extra checks needs to be done.

Could someone with a local coverity tool test if a cast similar to what was done in this patch for `sol_vector_append()` will fix it?

**Comment by vcgomes** [comment]
From this ( https://www.securecoding.cert.org/confluence/display/c/INT02-C.+Understand+integer+conversion+rules ) the C standard mandates that both operands are promoted to `signed int`s (as it can hold all values of an `uint16_t`).

**Comment by bdilly** [comment]
merged with @edersondisouza suggestion

**Pull request closed without merging**
