### PR TITLE
tools: Update calc-lib-size

### PR DESCRIPTION
**Pull request by anselmolsm**
As autogen.sh is gone, make this script it run
make alldefconfig && make

Signed-off-by: Anselmo L. S. Melo <anselmo.melo@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
seems good to me too

**Comment by lucasdemarchi** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 80574b6f7f1822b576f28d32999afd44896e5d76, new (rebased) HEAD is 4fd3b63a4ed8b72b173d06fca9468df42bd87f6e

**Comment by cmarcelo** [comment]
@anselmolsm one feature of calc-lib-size it was easy to compare different set of build options -- I cared mostly about disabling log to know the real code size.

By using make alldefconfig you prevent this. Maybe having a way to pass a config would be a good idea?

**Comment by cmarcelo** [comment]
E.g. `tools/calc-lib-size --with-maximum-internal-log-level=0`.

**Pull request closed without merging**
