### PR TITLE
Add HTTP generic node.

### PR DESCRIPTION
**Pull request by cabelitos**
Please look at https://github.com/solettaproject/soletta/issues/748

### CODE REVIEW

**Comment by barbieri** [comment]
This needs a careful review. Of both details and some key aspects.

In the details front, things like keeping http types in the sol-http header, not sol-types. Also using lookup tables for method to enum. Inspector formatting seems wrong and missing a "return" should be printing "<?>"

On the key aspects, "filter" is not good, I'd read it as "filter out", like remove. Use "get-" so we match JSON names. Also, headers (and maybe cookies?) are case Insensitive. And we need to start thinking how to make all of theses types extensible...we need to add too much boilerplate to introduce a new type! Maybe a new JSON in another directory to specify packets?

**Comment by barbieri** [comment]
And talk to @rchiossi, he implemented something like post with data. Maybe change his function to allow your needs?

**Comment by cabelitos** [comment]
@barbieri I agree with you, adding new packet types is always a pain. Maybe a json specification can help us indeed. 

Details: 
* I will talke a look at the inspector formation + return issue.
* I did not understand the part that you said 
* Should we keep the http types in sol-types.h even if sol is compiled without HTTP? I did not move those types there because, soletta can be compiled with support.

Keys -
* Maybe we should stay safe and compare all keys with strcasecmp() then.
* I will talk to @rchiossi about the post with data function

**Comment by cabelitos** [comment]
Closing in favor of #945

**Pull request closed without merging**
