### PR TITLE
Wallclock: Add option to send initial packets.

### PR DESCRIPTION
**Pull request by cabelitos**
For some applications sending an initial packet may be necessary.

Signed-off-by: Guilherme Iscaro de Godoy <guilherme.iscaro@intel.com>

### CODE REVIEW

**Comment by barbieri** [comment]
is it a problem if we send the initial packet? If no, then always send.

**Comment by cabelitos** [comment]
I talked to @bdilly about that and we concluded that leaving this as an option is the best thing to do,
because the user may want to be notified only once every minute.
If we send the initial packet by default, one can be notified twice in one minute. (In case that the user is using wallclock/minute)

**Comment by bdilly** [comment]
She won't be notified twice in the same minute, but the delta between initial packet and next packet may be much smaller then a minute. She can receive two packet in a timeframe smaller than a minute.
Is it a problem? Depends on the usage. I think that leaving it as an option is the safer approach for now, since we lack use cases.

**Comment by barbieri** [comment]
ok

**Comment by bdilly** [comment]
commit seems ok

**Comment by cabelitos** [comment]
@bdilly I tried to express what you said, maybe I was not clear enough :/
Anyway, thanks.

**Comment by cabelitos** [comment]
Merged

**Pull request closed without merging**
