### PR TITLE
Add HTTP client and Thingspeak node types

### PR DESCRIPTION
**Pull request by lpereira**
This PR adds the infrastructure to write HTTP clients. The API has been thought in a way that allows the backend to be changed without any changes; it's currently implemented with CURL, and the main loops have been properly integrated.

The ThingSpeak node types are being added as an example on how to use the HTTP Client APIs. No examples are being provided because API keys are needed; although the service is free, I'm not sure if it's a good idea to publish my test keys.

Each respective commit message contains more information.

I'm looking for feedback on the API, and, of course, for possible leaks and/or race conditions in the HTTP client.

### CODE REVIEW

**Comment by ceolin** [comment]
Please run uncrustify in the commits, there are a lot of small code style mistakes

**Comment by lpereira** [comment]
[**@ceolin**](https://github.com/ceolin) commented on [Jul 24, 2015, 2:41 PM GMT-3](https://github.com/solettaproject/soletta/pull/372#issuecomment-124594483 "2015-07-24T17:41:42Z - Replied by Github Comment Enhancer"):
> Please run uncrustify in the commits, there are a lot of small code style mistakes

This has been done and all mistakes have been fixed prior to submitting the PR.

**Comment by lpereira** [comment]
[**@barbieri**](https://github.com/barbieri) commented on [Jul 24, 2015, 5:11 PM GMT-3](https://github.com/solettaproject/soletta/pull/372#commitcomment-12351160 "2015-07-24T20:11:00Z - Replied by Github Comment Enhancer"):
> oops, this is curl function, so returning -1 is the way to go.

Done.

**Comment by lpereira** [comment]
Thanks, guys. I've made the requested changes locally. I'm closing this PR and will send a new revision after I've tested everything.

**Pull request closed without merging**
