### PR TITLE
Fix the build when SOCK_CLOEXEC and SOCK_NONBLOCK aren't defined

### PR DESCRIPTION
**Pull request by thiagomacieira**
Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>

### CODE REVIEW

**Comment by barbieri** [comment]
+1

but I wonder if we should introduce AF_UNIX to `sol_socket` so we can avoid doing manual socket in `unix-socket`. What do you think? @ceolin?

**Comment by thiagomacieira** [comment]
Makes sense, but the use is very limited now. Adding it to sol-socket would cause the non-Unix systems to have to show undefined for those cases...

Merge?

**Comment by ceolin** [comment]
i go with @thiagomacieira. I prefer don't introduce it on sol-socket if the only usage so far is those nodes. I think it's better do this manual than have to introduce support for it in N platforms, the chance of we break something when making changes is bigger.

**Comment by ceolin** [comment]
:+1:

**Comment by barbieri** [comment]
+1 for me

**Comment by bdilly** [comment]
Commit was merged through pr #1945 
Thanks

**Pull request closed without merging**
