### PR TITLE
Fixes related to options parsing

### PR DESCRIPTION
**Pull request by bdilly**
Please review it with attention since it may impact stuff
depending on conf files and we don't have much tests on that
(if any).

### CODE REVIEW

**Comment by ibriano** [comment]
Patches seem fine

**Comment by glima** [comment]
Okay for me too. I almost exploded when I looked at the size of that macro now :(

**Comment by lpereira** [comment]
A brave soul will eventually convert those macros to functions.

**Comment by bdilly** [comment]
@lpereira it isn't a bad idea. These macros are hard to maintain.

**Comment by bdilly** [comment]
Merged

**Pull request closed without merging**
