### PR TITLE
Lwm2m fixes

### PR DESCRIPTION
**Pull request by cabelitos**

### CODE REVIEW

**Comment by bdilly** [comment]
Everything seems good, except the (void)sol_ptr_vector_del() unnecessary usage

**Comment by bsmelo** [comment]
Looks very good to me.

Tested this standalone branch and two other branches I have (WIP for Access Control and a test client connecting with multiple servers at the same time) on top of these changes, and they solve a lot of the issues I had. :+1:

**Comment by cabelitos** [comment]
@bdilly I will remove that and create another commit removing all the casts to void from lwm2m

**Comment by cabelitos** [comment]
#2242

**Pull request closed without merging**
