### PR TITLE
Add composed packet types v2.

### PR DESCRIPTION
**Pull request by cabelitos**
* Added @barbieri and @edersondisouza suggestions.
* Added a commit to fix a crash when one tries to create a string packet with sol_flow_packet_new().

### CODE REVIEW

**Comment by edersondisouza** [comment]
I've tried to run `make check-fbp` on your branch, but it failed with:

       tuple.fbp:34:1 Couldn't resolve type 'tuple/string' of node '#anon:34:1'

Am I missing something? It appears to be searching a `tuple.so` module here.

I am also curious to see how a composed packet is printed on console, is there a way to see it?

**Comment by cabelitos** [comment]
I forgot to run the tests before pushing. I'm aware of the bug, I will fix it. Thanks @edersondisouza

**Comment by cabelitos** [comment]
@edersondisouza Did you try to erase your .config and generate it again?

**Comment by edersondisouza** [comment]
On 29-09-2015 09:36, Guilherme Íscaro wrote:
> @edersondisouza <https://github.com/edersondisouza> Did you try to erase
> your .config and generate it again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solettaproject/soletta/pull/795#issuecomment-144045929>.
>
In fact, it worked. Sorry for the noise.

**Comment by cabelitos** [comment]
Closing in favor of #806

**Pull request closed without merging**
