### PR TITLE
http:doc: Add snippet

### PR DESCRIPTION
**Pull request by ceolin**
Add a basic request snippet

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by ceolin** [comment]
@cmarcelo please take a look

**Comment by cmarcelo** [comment]
+1

**Comment by bdilly** [comment]
It looks good.

For future snippets I would recommend to actually using doxygen commands to show the code of one of our samples or tests, so we make sure it'll keep building and working fine. I believe it's more future-proof =)

But it's really nice, :+1:

**Comment by ceolin** [comment]
thank you guys

**Pull request merged**
