### PR TITLE
Minnow v2

### PR DESCRIPTION
**Pull request by mbelluzzo**
@edersondisouza now it should be gold ;-)

### CODE REVIEW

**Comment by bdilly** [comment]
@mbelluzzo Why are you letting two different checks for version intel-minnow-max-linux_gt_3_17 ?
If it's just because one it may matches with "^MNW2CRB1" or "MinnowBoard MAX"  can't you write something like "match": [ "^MNW2CRB1" ,"MinnowBoard MAX" ] in a single place?

I don't understand why are you keeping such related changes on two different commits too

**Comment by barbieri** [comment]
at least match as a single regexp: `"(^MNW2CRB1|MinnowBoard MAX)"` will match "MNW2CRB1" at the beginning of a line or "MinnowBoard MAX" anywhere.

**Comment by mbelluzzo** [comment]
@bdilly, the vector is a AND so we can't.  And this check is done in different files. Change the vector from and to OR would just cause some stuff to be impossible to be written, it was discussed when first implemented.

 @barbieri, again, different files.

**Comment by bdilly** [comment]
@mbelluzzo ok

I didn't test it.

Did @edersondisouza test it? If it worked fine for him, I'm ok with merging this pr.
(I'm supposing he had problems given the pr message).

**Comment by edersondisouza** [comment]
On 03-11-2015 15:33, Bruno Dilly wrote:
> @mbelluzzo <https://github.com/mbelluzzo> ok
>
> I didn't test it.
>
> Did @edersondisouza <https://github.com/edersondisouza> test it? If it
> worked fine for him, I'm ok with merging this pr.
> (I'm supposing he had problems given the pr message).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solettaproject/soletta/pull/999#issuecomment-153426890>.
>
Actually, I didn't test. PR message was about an issue I've found on 
previous version.

**Comment by mbelluzzo** [comment]
If there is no more objections, I'm going to merge this by the end of day.

**Comment by mbelluzzo** [comment]
Merged

**Pull request closed without merging**
