### PR TITLE
Remove nodejs binding

### PR DESCRIPTION
**Pull request by ceolin**
Nodejs binding was outdated and incomplete, as there is nobody
maintaining it we are removing it. This will make the build faster
and simplify the CI.
Whether somebody get interest in it again we can revert it.

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>

### CODE REVIEW

**Comment by glima** [comment]
Bunch of builds here and it seems we're fine. There's an unrelated issue, though, I want to sort out first: clean cashes/repo and make `alldefconfig; make -j check-fbp-bin` is screwing up ­— the module for js flow metatype is not being found prior to compiling the sample that has `MyScript` entry :(

**Comment by cabelitos** [comment]
Wow, the JS guys are not maintaining it anymore?

Is this the correct approach?

If we remove, we should remenber to change de CI rules so we don't try to execute the binding stuff.

**Comment by cabelitos** [comment]
@ceolin @glima ^

**Comment by glima** [comment]
Nope, no sign of them for a great deal of time, now. Well, we do not seem to have users of this part as well, and as you remembered, there's complexity on the CI as well to take care of. We should clean on that side as well, we are aware.

**Comment by ceolin** [comment]
@cabelitos agree about the CI, but  as the buildsystem itself does not have anything about js bindings anymore, even don't changing it now will not be a problem

**Comment by cabelitos** [comment]
ok then, +1

**Comment by cabelitos** [comment]
@ceolin I guess you forgot to close this PR.

**Comment by glima** [comment]
True, closing. I still want to figure out all build issues before proceeding with the release, doing that soon.

**Pull request closed without merging**
