### PR TITLE
HTTP get-json node.

### PR DESCRIPTION
**Pull request by cabelitos**

### CODE REVIEW

**Comment by barbieri** [comment]
@dorileo is doing a str slice trim equivalent as well, sync with him, he should send that one to master as that part is already good.

**Comment by cabelitos** [comment]
@barbieri got it.

**Comment by otaviobp** [comment]
+1

**Comment by cabelitos** [comment]
@glima,
@otaviobp is doing samples and @bdilly will prepare test for all http nodes.

**Comment by cabelitos** [comment]
Closing in favor of #979

**Pull request closed without merging**
