### PR TITLE
New features to sol_vector

### PR DESCRIPTION
**Pull request by cmarcelo**
`sol_vector_extend()` and always initialize to zero data passed to the user.

### CODE REVIEW

**Comment by cmarcelo** [comment]
@barbieri @vcgomes

**Comment by barbieri** [comment]
+1

**Comment by vcgomes** [comment]
The series looks good.

**Comment by cmarcelo** [comment]
Renamed to `append_n`, which describes better what it does than `extend`. Thanks @dorileo.

Applied in 0eaa532c16d64d94a1fea620071936eb27546969.

**Pull request closed without merging**
