### PR TITLE
Add sol-netctl API to get extra service properties v5

### PR DESCRIPTION
**Pull request by guchaojie**
This PR is for to improve getting extra service properties for user
All the properties provided by Connman D-Bus Hierarchy

Signed-off-by: guchaojie <chao.jie.gu@intel.com>

### CODE REVIEW

**Comment by guchaojie** [comment]
if [ $MASTER_BRANCH -eq 1 ]; then echo "Skip rebase for master branch"; else echo "Rebase on top of master branch"; BASECOMMIT="-b mainline/master" && git config user.name 'semaphoreci' && git config user.email 'semaphoreci@solettaproject.org' && git rebase mainline/master ; fi00:00
LINE WRAP OFF
Rebase on top of master branch
It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/home/runner/soletta/.git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.

I have already rebase my source code, why CI always failed for this error?

**Comment by ceolin** [comment]
@guchaojie not sure. I've not seen this problem before.
But, do not worry we'll ignore it and rebase directly (manually) on master (if necessary) before merge.

**Comment by guchaojie** [comment]
@ceolin @cabelitos @barbieri  source code has been updated according to V4 comments. However, the CI test still seems to have some issue, please have a review. Thanks.

**Comment by ceolin** [comment]
@guchaojie merged, thanks !!

**Pull request closed without merging**
