### PR TITLE
tools: toggle-config

### PR DESCRIPTION
**Pull request by cmarcelo**
Command line way to toggle a config option. Example usage

    $ tools/toggle-config use_icu
    # USE_ICU is not set

    Toggling and running make oldconfig

    USE_ICU=y

and the reverse also works

    $ tools/toggle-config use_icu
    USE_ICU=y

    Toggling and running make oldconfig

    # USE_ICU is not set

Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

### CODE REVIEW

**Comment by cmarcelo** [comment]
@dorileo @vcgomes could you look? Maybe there's a way to do this directly in kconfig that I'm missing.

**Comment by barbieri** [comment]
I think that just toggle is not that helpful. It would help to be able to get or set to a given value. toggle being an option.

Could you make it a:

```sh
   tools/kconfig-option --get use_icu
   tools/kconfig-option --set use_icu y
   tools/kconfig-option --set use_icu n
   tools/kconfig-option --set use_icu m # not really for icu, but you got the idea
   tools/kconfig-option --toggle use_icu # if y or m, then n. Otherwise then y? or m?
```

**Comment by vcgomes** [comment]
I agree with @barbieri, perhaps adding a `--force` option would be an acceptable middle ground?

**Comment by cmarcelo** [comment]
Nice suggestion, I'll try a v2 later and ping back. :-)

I disagree about toggle, though. I was in two situations already that I wanted to try/test something with an USE_ flag both enabled and disabled.

**Pull request closed without merging**
