### PR TITLE
sol-coap: Set sol_coap_msgtype_t when creating a new sol_coap_packet

### PR DESCRIPTION
**Pull request by cabelitos**
Signed-off-by: Guilherme Iscaro <guilherme.iscaro@intel.com>

@vcgomes @otaviobp Could you please take a look ?

### CODE REVIEW

**Comment by otaviobp** [comment]
+1

**Comment by glima** [comment]
Makes sense, +1

**Comment by vcgomes** [comment]
Looks good. :+1:

**Comment by cabelitos** [comment]
merged.

**Pull request closed without merging**
