### PR TITLE
Sol-platform: Remove the '\"' character from the locale if they it's …

### PR DESCRIPTION
**Pull request by cabelitos**
…present.

Signed-off-by: Guilherme Iscaro <guilherme.iscaro@intel.com>

### CODE REVIEW

**Comment by barbieri** [comment]
maybe handle single-quote as well? store the one found and check for it later.

**Comment by gabrielschulhof** [comment]
Oh, yeah! Definitely!

**Comment by cabelitos** [comment]
Damn, I forgot about them. I will create a v2

**Comment by cabelitos** [comment]
Check #1465

**Pull request closed without merging**
