### PR TITLE
Changes to modules int and boolean related to multiple ports and not filtering packets with the same value on these node types.

### PR DESCRIPTION
**Pull request by bdilly**
These modifications are consequence of discussions related to
pr #928

### CODE REVIEW

**Comment by otaviobp** [comment]
+1

**Comment by glima** [comment]
If the tests *and samples* are OK after that, go for it.

**Comment by bdilly** [comment]
@glima tests are OK for sure. I've tested a few samples using int arithmetic and they looked to be working fine.

**Comment by bdilly** [comment]
merged

**Pull request closed without merging**
