### PR TITLE
modules/flower-power improvements [v2]

### PR DESCRIPTION
**Pull request by bdilly**
Changelog:
 * drop changes on json parser and handle errors on module
 * cancel pending http requests
 * renames on init macro

### CODE REVIEW

**Comment by cabelitos** [comment]
+1

**Comment by bdilly** [comment]
Yeah, on i2c I would name it "handle" or "operation".
Naming a struct with an adjective instead of a noun doesn't seems clear to me, specially with one that is a temporary state (on some cases the connection won't be pending anymore, as it's the case of the finish_cb).
Also you're not sure what is pending. For http-client I was able to guess it was a connection, but for i2c I had to read the documentation.

**Comment by ceolin** [comment]
so go ahead, you're working closer this api than I. We still can change the i2c api soon :)

**Comment by bdilly** [comment]
merged with proposed change

**Pull request closed without merging**
