### PR TITLE
Add nodes to create JSON objects and JSON arrays - v3

### PR DESCRIPTION
**Pull request by otaviobp**
Changelog from v2:
 - Add commit changing type names of packets and using it in the commit that fixes composed bug
 - s/FLUSH/CLEAR port name
 - Improve CREATE port documentation
 - Use single pulse instead of timer in test. Also using new converter/string-to-json-*
 - Check strdup returns
 - Reorganizing functions and using extra_methods to reduce the number of duplicated functions

### CODE REVIEW

**Comment by otaviobp** [comment]
Replaces #918

**Comment by edersondisouza** [comment]
+1 No outstanding issues for me, but someone else looking over this series would be nice

**Comment by glima** [comment]
Looking ok for me too.

**Comment by otaviobp** [comment]
merged

**Pull request closed without merging**
