### PR TITLE
UART: Simplify API V3

### PR DESCRIPTION
**Pull request by zehortigoza**
Changes from V2:
- Change API to be like the API in GPIO and PWM.

### CODE REVIEW

**Comment by mbelluzzo** [comment]
Plz, squash everything in a single commit since you are doing most of the subsequent changes in the changes you have introduced in the first commit.

**Comment by zehortigoza** [comment]
The 3th is not changing in any code changed on the first 2 patches, I agree in squash the 1th and 2th but others are not related.

**Comment by mbelluzzo** [comment]
Deal! So squash the first and second and add a decent description to the fourth explaining what was improved in the sample. And plz don't forget to change the tables to "static const" and ad at least a minimal documentation that is something we are trying to improve in Soletta right now.

Besides these minors, it's a nice refactor ;-) thanks!

**Comment by zehortigoza** [comment]
New version https://github.com/solettaproject/soletta/pull/373

**Pull request closed without merging**
