### PR TITLE
Adding section on Contributing to the README.

### PR DESCRIPTION
**Pull request by lfelipe**
Signed-off-by: Luis Felipe Strano Moraes <luis.strano@intel.com>

### CODE REVIEW

**Comment by lpereira** [comment]
IANAL, but LGTM.

**Comment by thiagomacieira** [comment]
ACK.

I also recommend adding how to submit changes (i.e., GitHub PRs) and how to format commit messages. See https://github.com/torvalds/subsurface/blob/master/README#L71

**Comment by bdilly** [comment]
+2

**Comment by lucasdemarchi** [comment]
Applied

**Pull request closed without merging**
