### PR TITLE
style: force exactly one space before newline definition continuations.

### PR DESCRIPTION
**Pull request by glima**
Signed-off-by: Gustavo Lima Chaves <gustavo.lima.chaves@intel.com>

### CODE REVIEW

**Comment by glima** [comment]
I vote for at least committing the schema change, so we fix by chunks when needed.

**Comment by ceolin** [comment]
I'm ok with the schema :)

**Comment by glima** [comment]
@bdilly fine with committing just the schema file change as well?

**Comment by mbelluzzo** [comment]
I vote for merging everything. Git log is your friend

**Comment by bdilly** [comment]
@glima it seems a good approach. Just push the new schema and we change style when we need to modify these blocks.

**Comment by glima** [comment]
Works for me, pushing.

**Pull request closed without merging**
