### PR TITLE
iio: fix the logic error caused by code refactor

### PR DESCRIPTION
**Pull request by yongli3**
issue #2233

Signed-off-by: Yong Li <yong.b.li@intel.com>

### CODE REVIEW

**Comment by yongli3** [comment]
@laykuanloon please help to review

**Comment by laykuanloon** [comment]
Ok, The scale is working now.

**Comment by yongli3** [comment]
Thanks @laykuanloon I tested using light and proximity sensors, the data is okay now

**Comment by edersondisouza** [comment]
Merged, tks!

I failed to notice the issue, sorry.

**Pull request merged**
