### PR TITLE
Fix bug #1516:

### PR DESCRIPTION
**Pull request by otcyanglei**
update logging instantiation codes to solve issue when invoke the tools/run-fbp-tests with --log option
    refer to: https://docs.python.org/2/library/logging.html#module-level-functions

### CODE REVIEW

**Comment by barbieri** [comment]
:+1:

**Comment by otcyanglei** [comment]
I noticed there are CI fail when I re-commit.
By checking details, it seems the CI system got problem.

**Comment by cabelitos** [comment]
@otcyanglei I guess your patch is fine. I told the semaphore to try to build again.

**Comment by cabelitos** [comment]
+1

**Comment by bdilly** [comment]
Thanks, Lei Yang.
PR merged

**Pull request closed without merging**
