### PR TITLE
oic: Improve OIC documentation

### PR DESCRIPTION
**Pull request by otaviobp**
Depends on #1127. It is not possible to have the docs commit disassociated from #1127 because several changes in the API were introduced.

Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>

### CODE REVIEW

**Comment by edersondisouza** [comment]
Do not forget to see check-style issues.

**Comment by otaviobp** [comment]
waiting review on #1136 to merge this. Thanks

**Comment by mbelluzzo** [comment]
Isn't this #1136?

**Comment by otaviobp** [comment]
Sorry, waiting review of #1127 to merge this.

**Comment by otaviobp** [comment]
merged.

**Pull request closed without merging**
