### PR TITLE
v3: Add robotics module

### PR DESCRIPTION
**Pull request by lpereira**
This is the third version of the robotics module. Hopefully I've addressed all concerns from the previous versions (https://github.com/solettaproject/soletta/pull/1420 and https://github.com/solettaproject/soletta/pull/1264, respectively.)

### CODE REVIEW

**Comment by bdilly** [comment]
Aside from a very specific and easy to change points we've discussed on IRC, +1
So if you decide to just change and push direct to master, seems ok for me.

**Comment by edersondisouza** [comment]
What happened to this PR? Made its way to 'The Land of Forgotten Pulls'?

**Comment by bdilly** [comment]
@edersondisouza hehe, I believe I'll merge it.
I understand this code is good to be merged
If @lpereira decides to make other changes later it's fine.

**Comment by bdilly** [comment]
merged, thanks

**Pull request closed without merging**
