### PR TITLE
Add IIO node sample include Gryosope,Magnet, Accelerate, Color, Humidity, Light, ADC, Pressure and Temperature

### PR DESCRIPTION
**Pull request by guchaojie**
Change-Id: I5c8389510c91547b9617f4058ae5e302eec2ff09
Signed-off-by: guchaojie <chao.jie.gu@intel.com>

### CODE REVIEW

**Comment by guchaojie** [comment]
@barbieri @bdilly  @edersondisouza  This two category sensors test work well in Minnow Max board as reference by grove-kit, please have a review for these two category code style and picture. According to your comments and no problem, I will submit other sensor category as a bunch for further reviewing.Thanks

**Comment by barbieri** [comment]
looks excellent to me :-)

@mbelluzzo and @edersondisouza ?

**Comment by mbelluzzo** [comment]
\o/
+2

**Comment by guchaojie** [comment]
@barbieri @bdilly @edersondisouza All the IIO node samples have been submitted now, please have a review. If no problem, you can merge it. Thanks!

**Comment by mbelluzzo** [comment]
@edersondisouza we didn't demand, at least right now, pictures for all platforms. Just one, but I agree that would be nice to have a picture for configuration available, but would not block the PR because of this.

Regarding to sol-flow.conf, it will fallback to it in platforms other than the specified ones. That's also why there is no need to explain when to use each conf file, but rather explain what to do if your platform is neither minnow nor galileo. But one interesting thing that you brought to my attention is that if there is a sol-flow.json, it needs to be at least enough to successfully assemble the flow, IOW it need to have all required options on it so the nodes can be construct and everything, it may not work everywhere because options choices, but never for lack of required options. @guchaojie have you tested this?

**Comment by edersondisouza** [comment]
@mbelluzzo Oh, I see. Fair enough. And I don't think sol-flow.json is enough to build, as `iio_device` option doesn't have a default value.
@guchaojie Could you check this, please? Maybe just add the option with name of device for this fallback conffile.
And I was just curious about the Galileo photo =D

**Comment by barbieri** [comment]
Having a dummy `sol-flow.json` is good so at least the error message is more meaningful. It's easier to get an error that it failed to load due missing options, or the options do not match the hardware, instead of "MyGyroscope not found" and be clueless that it is missing a configuration file entry.

Thus keep the `sol-flow.json` as proposed in this PR.

As for PICTURES, I do have a comment: please name the files after the test so automated tools can link them (we'll provide those soon in "soletta's dev-app"). Then if the test is `temperature.fbp`, the schema should be called `schema-temperature.jpg`, not "-temperature-sensor" as it is now. It would also be better to name them after the current board in use, so the correct name would be: `schema-temperature-intel-minnow-max-linux_gt_3_17.jpg` (i know stating the kernel version in the board name is kinda weird, but hey... at least it is consistent).

The plan is for the GUI to show the configuration file for that FBP and when you press "run" it will first show the assembly picture (`schema-${FBP}-${BOARD_NAME}.jpg`)

**Comment by guchaojie** [comment]
@edersondisouza @mbelluzzo ADC module is built in the Galileo board, so there is no wiring picture in this PR.
There are two reasons putting sol-flow.json here:
 1. sol-flow.json is dummy now but just for fallback conffile in the future. According my test, if we want to sol-flow.json take effect, we have to let this sol-flow.json include all the option detail for different platform like sol-flow-intel-minnow-max-linux_gt_3_17.json.
2. According to  https://github.com/solettaproject/soletta/blob/master/src/samples/flow/grove-kit/README, I found one error happen
 $ ./grove-button.fbp
./grove-button.fbp:37:1 Couldn't resolve type name 'Button'
It shows that defining sol-flow.json  in the current folder can avoid this.

**Comment by guchaojie** [comment]
What's your point for sol-flow.json to keep current style or add all the required options for different platform into it?

**Comment by edersondisouza** [comment]
Ah, ok about the picture then =D
Keep sol-flow.json as is, just fix the comments and image names as @barbieri proposed.

**Comment by guchaojie** [comment]
@edersondisouza I have already fixed the issue about comments and image name, BTW, add README file according to your suggestion, please have a review:)

**Comment by bdilly** [comment]
@guchaojie pr seems good.

I've invited you to join soletta-dev teams, so you'll be able to push your changes to master.
Just check our approach before doing it. We're not following regular github flow.

https://github.com/solettaproject/soletta/wiki/Contributing#contributions-flow

Special attention to step 8.

Thanks

**Comment by mbelluzzo** [comment]
+2 @guchaojie take the opportunity to test if you can successfully merge this!

**Comment by guchaojie** [comment]
According to previous experience, we push the button to merge PR in github. 
And I misunderstand  https://github.com/solettaproject/soletta/wiki/Contributing#contributions-flow just states that how a soletta developer push his own source code from local reviewed_branch not for every review source code PR which need to do these steps too. When I git log in the master branch,  I found that we push the merge button wrongly.
And I want to repair the commit statement by trying two methods:
1. git reset --hard HEAD^  & git apply 1443.patch & git push  (failed because protected branch hook declined)
2. git checkout reviewed_branch & rebase the branch & git commit -s --amend(modify the commit message) & git push origin HEAD:master (failed because a pushed branch tip is behind its remote)
However, both cannot take effect . 
So can anyone tell me how to remedy this commit in the master branch?

**Comment by edersondisouza** [comment]
Hi,

We are not using merge commits, that's why we don't push Github merge button - we rebase our changes on top of current master and send it with `git push`.
As we also do not allow 'force pushes' on master, I'd say that there's nothing to do about this merge - but be more careful next time =D

**Comment by bdilly** [comment]
@guchaojie that's ok. Next time, when you face any problem, any unexpected situation, or you see something doesn't seem clear, please talk to us first. There's nothing we can do about what was done. We shouldn't change master branch history, never. Lot's of developers we'll be working on top of this branch, so you may affect the work of all of them. It's a bad practice. Fortunately github allows us to deny this kind of change, and we're using this feature.

In our instructions there isn't anything about using a  "merge button", right? There are a few git commands that should be used instead.

We prefer to keep our repository history more linear.

Anyway, I've asked another engineer to review these instructions to make it more clear.
Please feel free to make suggestion as well, or even edit the wiki page to avoid that others developers make the same mistake in the future.

Thanks

**Comment by glima** [comment]
* Bruno Dilly <notifications@github.com> [2016-02-25 07:08:45 -0800]:

> @guchaojie that's ok. Next time, when you face any problem, any unexpected situation, or you see something doesn't seem clear, please talk to us first. There's nothing we can do about what was done. We shouldn't change master branch history, never. Lot's of developers we'll be working on top of this branch, so you may affect the work of all of them. It's a bad practice. Fortunately github allows us to deny this kind of change, and we're using this feature.
> 
> In our instructions there isn't anything about using a  "merge button", right? There are a few git commands that should be used instead.
> 
> We prefer to keep our repository history more linear.
> 
> Anyway, I've asked another engineer to review these instructions to make it more clear.
> Please feel free to make suggestion as well, or even edit the wiki page to avoid that others developers make the same mistake in the future.

And it's done. I hope we're more clear now.

> 
> Thanks
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/solettaproject/soletta/pull/1443#issuecomment-188827779

-- 
Gustavo Lima Chaves
Intel - Open Source Technology Center

**Pull request merged**
