### PR TITLE
log: Fix extern log domain variable names so they don't clash

### PR DESCRIPTION
**Pull request by glima**
when we built all modules as built-in.

Signed-off-by: Gustavo Lima Chaves <gustavo.lima.chaves@intel.com>

### CODE REVIEW

**Comment by mbelluzzo** [comment]
+2

**Comment by ricardotk** [comment]
ACK.
minor: what do you think about add this kind of prefix in all the other places where we use log domain variables?

**Comment by glima** [comment]
@ricardotk The common case is to have these variables declared as *static*, so we're safe.

**Comment by ricardotk** [comment]
Ok, good

**Comment by glima** [comment]
Merged.

**Pull request closed without merging**
