### PR TITLE
Regexp [v2]

### PR DESCRIPTION
**Pull request by glima**
Changes since v1:

Errors pointed by @edersondisouza fixed (leak, bad define removal, etc), warning messages now make use of new @dorileo 's schema (we just need that after the config phase now), new help string for the string nodes at the config phase.

### CODE REVIEW

**Comment by glima** [comment]
There's also a new commit fixing misuse of  sol_flow_send_error_packet throughout the code.

**Comment by edersondisouza** [comment]
+1

**Comment by edersondisouza** [comment]
@glima Remember to update wiki about dependences when this series goes in.

**Comment by glima** [comment]
Ack! Should you raise your review to +2 and I'll do it right away :)
Also, I removed some redundant nested ifdefs there.

**Comment by edersondisouza** [comment]
Hehe. lgtm, but not sure about build stuff that @dorileo is the one who knows =D

**Comment by dorileo** [comment]
I didn't check in depth the added C code, but what concerns build system it's ok.
+1

**Comment by glima** [comment]
Alright, merging.

**Pull request closed without merging**
