### PR TITLE
Nodejs oic bindings v3

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Replaces #1608.

* Addressed review comments

### CODE REVIEW

**Comment by poussa** [comment]
Based on @barbieri comment on v2, we can merge/commit this.

**Comment by otaviobp** [comment]
if you fixed the comments @ceolin did, just go ahead and merge it.

**Comment by ceolin** [comment]
:+1: to me. Please feel free to commit these commits.

**Comment by gabrielschulhof** [comment]
Will do ASAP. Thanks for the review!

**Pull request closed without merging**
