### PR TITLE
Client fixes

### PR DESCRIPTION
**Pull request by ceolin**
- Handle curl's timer properly
- Fix possible race condition
- Fix possible segfault

### CODE REVIEW

**Comment by lpereira** [comment]
LGTM with @barbieri's comment.

**Comment by ceolin** [comment]
thanks guys, @bdilly could check this pullreq please?

**Comment by bdilly** [comment]
@ceolin It's working fine and valgrind is happy =D

**Comment by ceolin** [comment]
merged, thank you all

**Pull request closed without merging**
